version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres-benefit
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null